username,stars,repo_name,repo_url
Genymobile,47700,scrcpy,https:/github.com/Genymobile/scrcpy
neovim,43300,neovim,https:/github.com/neovim/neovim
git,37700,git,https:/github.com/git/git
fffaraz,31000,awesome-cpp,https:/github.com/fffaraz/awesome-cpp
obsproject,27500,obs-studio,https:/github.com/obsproject/obs-studio
serhii-londar,25800,open-source-mac-os-apps,https:/github.com/serhii-londar/open-source-mac-os-apps
FFmpeg,24400,FFmpeg,https:/github.com/FFmpeg/FFmpeg
vim,23500,vim,https:/github.com/vim/vim
ggreer,21900,the_silver_searcher,https:/github.com/ggreer/the_silver_searcher
curl,20400,curl,https:/github.com/curl/curl
huihut,18200,interview,https:/github.com/huihut/interview
ruby,18100,ruby,https:/github.com/ruby/ruby
google,16100,flatbuffers,https:/github.com/google/flatbuffers
oracle,15100,graal,https:/github.com/oracle/graal
mpv-player,14900,mpv,https:/github.com/mpv-player/mpv
shadowsocks,14300,shadowsocks-libev,https:/github.com/shadowsocks/shadowsocks-libev
radareorg,14300,radare2,https:/github.com/radareorg/radare2
pbatard,13600,rufus,https:/github.com/pbatard/rufus
vurtun,13300,nuklear,https:/github.com/vurtun/nuklear
allinurl,13100,goaccess,https:/github.com/allinurl/goaccess
microsoft,12600,vcpkg,https:/github.com/microsoft/vcpkg
facebook,12200,infer,https:/github.com/facebook/infer
CoatiSoftware,11200,Sourcetrail,https:/github.com/CoatiSoftware/Sourcetrail
jarun,11200,nnn,https:/github.com/jarun/nnn
kovidgoyal,11100,kitty,https:/github.com/kovidgoyal/kitty
s-matyukevich,10200,raspberry-pi-os,https:/github.com/s-matyukevich/raspberry-pi-os
jonas,10000,tig,https:/github.com/jonas/tig
hashcat,9700,hashcat,https:/github.com/hashcat/hashcat
qmk,9400,qmk_firmware,https:/github.com/qmk/qmk_firmware
OpenRCT2,9300,OpenRCT2,https:/github.com/OpenRCT2/OpenRCT2
